#!/bin/bash
set -e # exit immediately if any command fails

if [ "$1" = "--link" ]; then
    echo "Skipping compilation..."
else
    if ! cabal run haskell-cc -- test.c; then
        echo "Compilation failed"
        exit 1
    fi
fi

as -o output.o output.asm
clang -o program.out output.o -lc
